spring.datasource.url=jdbc:mysql://terraform-20250507100115548600000007.clm26o4g8bqn.us-east-2.rds.amazonaws.com/springbackend?useSSL=false
spring.datasource.username=admin
spring.datasource.password=Redhat123

spring.jpa.generate-ddl=true
